// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ObUOCpQ3NDcr1vIIdYT2f1wPIfVW1m8',
    appId: '1:242126486134:web:f98f2f880a46b81e3cbd57',
    messagingSenderId: '242126486134',
    projectId: 'scholar-app-bd12a',
    authDomain: 'scholar-app-bd12a.firebaseapp.com',
    storageBucket: 'scholar-app-bd12a.appspot.com',
    measurementId: 'G-7VWLXGBCCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxboop_w94VtfiOEesk5FwVOWqfOxD3gA',
    appId: '1:242126486134:android:1edb4a98a54000b53cbd57',
    messagingSenderId: '242126486134',
    projectId: 'scholar-app-bd12a',
    storageBucket: 'scholar-app-bd12a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xR8yA_YE-eJ4Uzpy7vXyDkxX1zTLO_g',
    appId: '1:242126486134:ios:4139935561d2e3dd3cbd57',
    messagingSenderId: '242126486134',
    projectId: 'scholar-app-bd12a',
    storageBucket: 'scholar-app-bd12a.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xR8yA_YE-eJ4Uzpy7vXyDkxX1zTLO_g',
    appId: '1:242126486134:ios:4139935561d2e3dd3cbd57',
    messagingSenderId: '242126486134',
    projectId: 'scholar-app-bd12a',
    storageBucket: 'scholar-app-bd12a.appspot.com',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0ObUOCpQ3NDcr1vIIdYT2f1wPIfVW1m8',
    appId: '1:242126486134:web:d37db42c2cfa26d33cbd57',
    messagingSenderId: '242126486134',
    projectId: 'scholar-app-bd12a',
    authDomain: 'scholar-app-bd12a.firebaseapp.com',
    storageBucket: 'scholar-app-bd12a.appspot.com',
    measurementId: 'G-DMCEJNMQ2S',
  );
}
